# Load packages
library(phyloseq) 
library(tidyverse)
library(vegan)
library(ade4)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(maps)
library(maptools)
library(tools)
library(ggmap)
library(ggbiplot)
library(microbiome)
library(RColorBrewer)
library(dada2)
library(ecodist)
library(modelr)
